[config]
device=xilinx0:0

# set cpucore=-1 to disable cpu binding
cpucore=10

# license key
license=KkRBeU5qSTBPQT49$LWpBeU5URXlNhkU9

# 0 to 3 bits, respectively, are the error, warning, info, and debug log level bits. When the corresponding bit is set to 1, record the corresponding level log information
log_level=15

#level1 input network Port, Value range [0-1], Default value 0
level1_netport=0
#level2 input network Port, Value range [0-1], Default value 0
level2_netport=0

# multi addr and port
multi_ipport_A=239.8.8.8:12581
multi_ipport_B=239.8.8.9:12581

# Network version configuration item, copying 0 channel subscription contract market push
DSTMAC=00:0f:53:a0:2b:81
DSTIP=10.10.20.10
DSTPORT=5000

SRCMAC=64:3f:5f:01:02:03
SRCIP=10.10.20.100
SRCPORT=1234

[channel0]
# subscribe instruments, e.g. all to receive all instruments, or fb2309,jd2404,lh2401 split instruments with comma
insts=all
#active only if insts=all or subscribe instruments with variety like ag or bu etc.
options=recv
sp_spc=norecv

[channel1]
# subscribe instruments, e.g. all to receive all instruments, or fb2309,jd2404,lh2401 split instruments with comma
insts=jm2601
#active only if insts=all or subscribe instruments with variety like ag or bu etc.
options=recv
sp_spc=norecv

