[config]
device=xilinx0:0
# set cpucore=-1 to disable cpu binding
cpucore=5
ine2ps=disabled
shfe2ps=enabled
shfe4ps=disabled
ine4ps=enabled

# SHFE A/B 2ps/4ps, change only if SHFE change them.
shfe2ps_ip_a=239.3.42.71:21000
shfe2ps_ip_b=239.4.42.72:21000
shfe4ps_ip_a=239.3.2.3:21101
shfe4ps_ip_b=239.4.2.4:21101

# INE A/B 2ps/4ps, change only if INE change them.
ine2ps_ip_a=239.3.52.71:25000
ine2ps_ip_b=239.4.52.72:25000
ine4ps_ip_a=239.3.151.91:25101
ine4ps_ip_b=239.4.151.92:25101

# SHFE/INE topic id, change only if SHFE/INE change them.
shfe2ps_topic_id=1000
shfe4ps_topic_id=1101
ine2ps_topic_id=5000
ine4ps_topic_id=5101

# SHFE/INE TCP Snap port, change only if SHFE/INE change them.
shfe2ps_snap_port=33022
shfe4ps_snap_port=22000
ine2ps_snap_port=33022
ine4ps_snap_port=22000

# Does the startup wait for the snapshot to initialize the FPGA based on changes in the configuration file crc
crc_mux_check=0

# 0 to 15 bit identify whether the corresponding channel has the last tick enabled. Corresponding maximum contract number of the subject.
last_tick_channel=0
shfe2ps_max_inst_no=81000
shfe4ps_max_inst_no=81101
ine2ps_max_inst_no=85000
ine4ps_max_inst_no=85101

# license key
license=KkRBeU5qSTBPQT49$LWpBeU5URXlNhkU9

# 0 to 3 bits, respectively, are the error, warning, info, and debug log level bits. When the corresponding bit is set to 1, record the corresponding level log information
# Support specified log path ,must modify all config_*.ini .  eg.  log_path=/  
log_level=15

# Network version configuration item, copying 0 channel subscription contract market push
DSTMAC=01:00:5E:01:02:03
DSTIP=224.1.2.3
DSTPORT=5000

SRCMAC=64:3f:5f:01:02:03
SRCIP=10.253.1.115
SRCPORT=1234

[channel0]
# subscribe instruments, e.g. all to receive all instruments, or ag2201,bu,ag2306P5800
insts=all
options=recv

[channel1]
insts=ag2512P6700,ag2510,ag2509P9,cu2509,fu,ni,rb2507C2800
options=recv

[channel2]
insts=ag2512P6700,ag2510,ag2509P9
options=norecv

[channel3]
insts=ag,al,al,au2504,sc25
options=norecv

[channel4]
insts=all
options=recv

#[channel5]
#insts=pb,ni,fu,cu,au
#options=norecv



