#ifndef MARKET_MAKER_STRATEGY_ERROR_ID_H
#define MARKET_MAKER_STRATEGY_ERROR_ID_H
namespace cffex{
namespace   fb{
enum {
    STRATEGY_ERROR_NONE = 0,  // 成功
    STRATEGY_ERROR_UNKNOWN = -1,  // FEBAO:未知错误
    STRATEGY_ERROR_SYSTEM_IN_INIT = 1,  // FEBAO:系统未启动完成
    STRATEGY_ERROR_PRICE_OUT_OF_LOWER_LIMIT = 2,  // FEBAO:价格超出下限
    STRATEGY_ERROR_PRICE_OUT_OF_UPPER_LIMIT = 3,  // FEBAO:价格超出上限
    STRATEGY_ERROR_INVALID_QUOTE_PRICE = 4,  // FEBAO:非法的报价价格
    STRATEGY_ERROR_INVALID_VOLUME = 5,  // FEBAO:非法的数量
    STRATEGY_ERROR_RISK_SELF_TRADE = 6,  // FEBAO:订单触发自成交
    STRATEGY_ERROR_RISK_MAX_ORDER_LIMIT = 7,  // FEBAO:最大报单量检查失败
    STRATEGY_ERROR_RISK_POSITION_LIMIT = 8,  // FEBAO:持仓限额检查失败
    STRATEGY_ERROR_RISK_FLOW_LIMIT = 9,  // FEBAO:超过流控限制
    STRATEGY_ERROR_TRY_FROZEN_POSITION = 10,  // FEBAO:持仓冻结失败
    STRATEGY_ERROR_TRY_INCREASE_ORDERBOOK = 11,  // FEBAO:订单簿更新失败
    STRATEGY_ERROR_COUNTER_TIMEOUT = 12,  // FEBAO:柜台响应超时
    STRATEGY_ERROR_NO_MARKET_DATA = 13,  // FEBAO:该合约没有基础行情
    STRATEGY_ERROR_OUTSIDE_SELF_TRADE_CHECK_FAILED = 14,  // FEBAO:该合约系统外部风控检查失败
    STRATEGY_ERROR_OUTSIDE_SELF_TRADE_CHECK_TIMEOUT = 15,  // FEBAO:该合约系统外部风控检查超时
    STRATEGY_ERROR_PORTFOLIO_NOT_EXIST_OR_INACTIVE = 16,  // FEBAO:组合不存在或失效
    STRATEGY_ERROR_COUNTER_FAILED = 17,  // FEBAO:柜台调用失败
    STRATEGY_ERROR_ORDER_RISK_CHECK_FAILED = 18,  // FEBAO:该笔委托存在业务风险
    STRATEGY_ERROR_FUND_CHECK_FAILED = 19,  // FEBAO:资金可用不足
    STRATEGY_ERROR_ROOTNET_RISK_FAILED = 20,  // FEBAO:根网风控检查失败
    STRATEGY_ERROR_ROOTNET_OUTSIDE_SELF_TRADE_CHECK_FAILED = 21,  // FEBAO:根网系统间防对敲检查失败
    STRATEGY_ERROR_INSTRUMENT_POSITION_OUT_OF_CLIENT_LIMIT = 22,  // FEBAO:合约持仓量超过客户允许最大持仓量
    STRATEGY_ERROR_INSUFFICIENT_POSITION = 23,  // FEBAO:持仓份额不足
    STRATEGY_ERROR_CANCEL_ORDER_FAILED = 24,  // FEBAO:撤单失败
    STRATEGY_ERROR_CANCEL_ALL_TRADE = 25,  // FEBAO:全部成交撤单失败
    STRATEGY_ERROR_CANCEL_EXCHANGE_FLOW_LIMIT = 26,  // FEBAO:交易所流控撤单失败
    STRATEGY_ERROR_CANCEL_COUNTER_FLOW_LIMIT = 27,  // FEBAO:柜台流控撤单失败
    STRATEGY_ERROR_NO_INSERT_ORDER_RIGHT = 28,  // FEBAO:禁止报单
    STRATEGY_ERROR_NO_INSERT_QUOTE_RIGHT = 29,  // FEBAO:禁止报价
    STRATEGY_ERROR_NO_CANCEL_ORDER_RIGHT = 30,  // FEBAO:禁止撤销报单
    STRATEGY_ERROR_NO_CANCEL_QUOTE_RIGHT = 31,  // FEBAO:禁止撤销报价
    STRATEGY_ERROR_NO_OPEN_OFFSET_RIGHT = 32,  // FEBAO:禁止开仓
    STRATEGY_ERROR_NO_CLOSE_OFFSET_RIGHT = 33,  // FEBAO:禁止平仓
    STRATEGY_ERROR_OFFSET_FLAG = 34,  // FEBAO:开平标志错误
    STRATEGY_ERROR_MANUAL_DELETE = 35,  // FEBAO:交易员标记错单
    STRATEGY_ERROR_NO_SELF_TRADE_CONFIG = 36,  // FEBAO:找不到自成交配置
    STRATEGY_ERROR_TRADING_NOT_FINISH_INITED = 37,  // FEBAO:交易模块未完成初始化
    STRATEGY_ERROR_INVALID_OUTSIDE_SELF_TRADE_CONFIG = 38,  // FEBAO:该产品系统外部风控配置错误
    STRATEGY_ERROR_CANCEL_ORDER_NOT_FOUND = 39,  // FEBAO:撤单找不到相应报单
    STRATEGY_ERROR_CANCEL_INSUITABLE_ORDER_STATUS = 40,  // FEBAO:报单已全成交或已撤销，不能再撤
    STRATEGY_ERROR_CANCEL_QUOTE_NOT_FOUND = 41,  // FEBAO:报价撤单找不到相应报价
    STRATEGY_ERROR_CANCEL_QUOTE_DERIVEDORDER = 42,  // FEBAO:报价衍生单要等待交易所返回才能撤单
    STRATEGY_ERROR_CANCEL_COUNTER_TRANSIT_FLOW_LIMIT = 43,  // FEBAO:柜台在途流控撤单失败
    STRATEGY_ERROR_CANCEL_TIMEOUT_ORDER = 44,  // FEBAO:超时单撤单失败
    STRATEGY_ERROR_CANCEL_FINAL_ORDER = 45,  // FEBAO:终态单撤单失败
    STRATEGY_ERROR_CANCEL_FINAL_QUOTE = 46,  // FEBAO:终态报价单撤单失败
    STRATEGY_ERROR_NO_TRADE = 47,  // FEBAO:删除簿记找不到成交失败
    STRATEGY_ERROR_NOT_BOOK_TRADE = 48,  // FEBAO:删除非簿记成交失败
    STRATEGY_ERROR_RISK_GREEKS = 49,  // FEBAO:GREEKS风控失败
    STRATEGY_ERROR_TRADING_PROXY_TIMEOUT = 50,  // FEBAO:交易接入响应超时
    STRATEGY_ERROR_RISK_NET_POSITION_EXCEEDED = 51,  // FEBAO:净持仓超限禁止交易
    STRATEGY_ERROR_RISK_MAX_ORDER_CANCEL_COUNT_LIMIT = 52,  // FEBAO:超过该合约的最大撤单笔数
    STRATEGY_ERROR_CANCEL_TIMEOUT_QUOTE = 53,  // FEBAO:超时报价单撤单失败
    STRATEGY_ERROR_PROXY_CALL_API_FAIL = 54,  // FEBAO:接入调用api失败
    };
 }
}
#endif
