[config]
device=xilinx0:0

# set cpucore=-1 to disable cpu binding
cpucore=10

# license key
license=KXpBeE5UTTFOZz49$LWpBeU5qQTRNhkU9

# 0 to 3 bits, respectively, are the error, warning, info, and debug log level bits. When the corresponding bit is set to 1, record the corresponding level log information
log_level=15

#Default format:/root/xxx,There should be no ending '/'
#log_path=/home

# Network version configuration item, copying 0 channel subscription contract market push
DSTMAC=01:00:5e:01:02:09
DSTIP=239.01.02.09
DSTPORT=5000

SRCMAC=64:3f:5f:01:02:03
SRCIP=10.10.20.100
SRCPORT=1234

[channel0]
# subscribe instruments, e.g. all to receive all instruments, or fb2309,jd2404,lh2401 split instruments with comma
insts=lc2510,si2510
#active only if insts=all or subscribe instruments with variety like ag or bu etc.
options=recv
sp_spc=norecv
