;该配置是DS场景的接入配置模板
;目前支持接入上海市场,深圳市场,股转市场,北京市场
;            上期所,大商所,郑商所,中金所,能源,申万指数
;只支持TCP接入DS
[nsq_api]
console_output_log=1                     ;是否在控台输出日志信息。0表示不输出，1表示输出。默认为1。

support_markets=sh,sz                    ;支持的市场类别。以逗号分隔，和下面市场key对应,目前支持sh、sz、shfe、dce、czce、cffex、ine、neeq、bj
                                         ;shfe上期所, dce大商所, czce郑商所, cffex中金所, ine能源, neeq股转, bj北交所


;用户登录、接收代码表等信息的tcp通道
service_addr=192.168.1.168               ;行情周边服务侦听TCP服务地址, 行情周边服务指sailfish_service
service_port=8888                        ;行情周边服务侦听TCP服务端口

;用户登录、接收代码表等信息的tcp冷备通道
service_addr1=192.168.1.169              ;行情周边服务侦听TCP服务冷备地址, 行情周边服务指sailfish_service
service_port1=8888                       ;行情周边服务侦听TCP服务冷备端口

;开户绑定mac地址对应网卡配置，用户登录行情服务校验使用
auth_interface_ip=192.168.1.189          ;获取该ip对应的网卡mac地址，用于权限服务系统校验


[sh]
session_num=1                            ;开启session数量
timeout=20                               ;超时时间20秒,至少大于网关超时时间两倍以上

;逐笔重建服务地址
;rebuild_addr=10.20.33.2
;rebuild_port=39127

[sh_session1]
recv_buf_size=128                        ;接收组播行情的UDP缓存大小，单位M
session_cpu_affinity=5                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持5,6,7或者5-7配置方式
                                         ;sh_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;sh_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu
										 ;该session启用可靠组播地址时，需要多配置几个cpu(一个地址一个cpu)给可靠组播绑核接收数据(可选)
										
;nsq行情主地址列表, 多路同时接收数据
[sh_session1_rpc_hot]
;接收NSQ TCP行情主地址
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=17888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，1-sailfish, 4-DS, 5-HQReceiverGW; 默认为1-sailfish

;nsq行情温备地址列表
[sh_session1_rpc_warm]
;接收NSQ TCP行情主地址
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=17887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，1-sailfish, 4-DS, 5-HQReceiverGW; 默认为1-sailfish

;nsq行情冷备地址列表，注意level1地址只能配置在冷备地址列表
[sh_session1_rpc_cold]
;接收NSQ TCP行情主地址
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=17886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，1-sailfish, 4-DS, 5-HQReceiverGW; 默认为1-sailfish

[sz]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于网关超时时间两倍以上；如果接入FPGA协议超时时间需配置60秒以上

;逐笔重建服务地址
;rebuild_addr=10.20.33.2
;rebuild_port=39127

[sz_session1]
recv_buf_size=128                        ;接收组播行情的UDP缓存大小，单位M
session_cpu_affinity=3                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;sz_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;sz_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu
                                         ;该session启用可靠组播地址时，需要多配置几个cpu(一个地址一个cpu)给可靠组播绑核接收数据(可选)

;nsq行情主地址列表, 可以启用多路地址同时接收数据
[sz_session1_rpc_hot]
;接收NSQ TCP行情配置
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=18888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，1-sailfish, 4-DS, 5-HQReceiverGW; 默认为1-sailfish

;nsq行情温备地址列表
[sz_session1_rpc_warm]
;接收NSQ TCP行情配置
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=18887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，1-sailfish, 4-DS, 5-HQReceiverGW; 默认为1-sailfish

;nsq行情冷备地址列表，注意level1地址只能配置在冷备地址列表
[sz_session1_rpc_cold]
;接收NSQ TCP行情配置
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=18886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，1-sailfish, 4-DS, 5-HQReceiverGW; 默认为1-sailfish


[neeq]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于DS超时时间两倍以上

[neeq_session1]
recv_buf_size=128                        ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;neeq_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;neeq_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu

;nsq行情主地址列表, 可以启用多路地址同时接收数据
[neeq_session1_rpc_hot]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低

;nsq行情温备地址列表
[neeq_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低

;nsq行情冷备地址列表
[neeq_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低

[bj]
session_num=1                             ;开启session数量
timeout=60                                ;超时时间60秒，至少大于DS超时时间两倍以上

[bj_session1]
recv_buf_size=128                                ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                           ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                                 ;bj_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                                 ;bj_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu

;nsq行情主地址列表, 可以启用多路地址同时接收数据
[bj_session1_rpc_hot]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低

;nsq行情温备地址列表
[bj_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低

;nsq行情冷备地址列表
[bj_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低


[shfe]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于DS超时时间两倍以上

[shfe_session1]
recv_buf_size=128                        ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;shfe_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;shfe_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu


;nsq行情主地址列表, 可以启用多路地址同时接收数据
[shfe_session1_rpc_hot]
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情温备地址列表
[shfe_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情冷备地址列表
[shfe_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS


[dce]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于DS超时时间两倍以上

[dce_session1]
recv_buf_size=128                        ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;dce_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;dce_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu


;nsq行情主地址列表, 可以启用多路地址同时接收数据
[dce_session1_rpc_hot]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情温备地址列表
[dce_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情冷备地址列表
[dce_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS


[czce]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于DS超时时间两倍以上

[czce_session1]
recv_buf_size=128                        ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;czce_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;czce_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu


;nsq行情主地址列表, 可以启用多路地址同时接收数据
[czce_session1_rpc_hot]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情温备地址列表
[czce_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情冷备地址列表
[czce_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS


[cffex]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于DS超时时间两倍以上

[cffex_session1]
recv_buf_size=128                        ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;cffex_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;cffex_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu


;nsq行情主地址列表, 可以启用多路地址同时接收数据
[cffex_session1_rpc_hot]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情温备地址列表
[cffex_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情冷备地址列表
[cffex_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS


[ine]
session_num=1                            ;开启session数量
timeout=60                               ;超时时间60秒，至少大于DS超时时间两倍以上

[ine_session1]
recv_buf_size=128                        ;接收DS TCP行情缓存大小，单位M
session_cpu_affinity=1                   ;通道所属线程绑定到的cpu列表，以0开始，配置多个cpu时,支持3,4或者3-4配置方式
                                         ;ine_session1_rpc_hot地址列表只启用一个地址，可只配置一个cpu
                                         ;ine_session1_rpc_hot地址列表启用N个地址时，需配置N+1个cpu


;nsq行情主地址列表, 可以启用多路地址同时接收数据
[ine_session1_rpc_hot]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=1                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19888                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS


;nsq行情温备地址列表
[ine_session1_rpc_warm]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19887                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

;nsq行情冷备地址列表
[ine_session1_rpc_cold]
;接收DS TCP行情配置，只支持TCP，配置其他类型地址无效
server_enable=0                          ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收tcp行情的服务端ip，主地址
server_port=19886                        ;接收tcp行情的服务端端口
server_priority=0                        ;地址优先级。取值0~9，数值大优先级低
server_source_type=4                     ;上级源类型，4-DS, 5-HQReceiverGW; 默认为4-DS

