;该配置是期现环网的接入配置模板
;只支持TCP接入行情网关
[nsq_api]
console_output_log=1                     ;是否在控台输出日志信息。0表示不输出，1表示输出。默认为1。

;开户绑定mac地址对应网卡配置，用户登录行情服务校验使用
auth_interface_ip=192.168.1.189          ;获取该ip对应的网卡mac地址，用于权限服务系统校验

;上证逐笔重建服务地址1
;sh_rebuild_addr=10.20.33.2
;sh_rebuild_port=39127
;上证逐笔重建服务地址2                   ;支持双路rebuild同时接入，用户请求重建，只要任何一路有重建请求需要的数据，可完成数据补全
;sh_rebuild_addr1=10.20.33.2
;sh_rebuild_port1=39128

;深证逐笔重建服务地址1
;sz_rebuild_addr=10.20.33.2
;sz_rebuild_port=39127
;深证逐笔重建服务地址2                   ;支持双路rebuild同时接入，用户请求重建，只要任何一路有重建请求需要的数据，可完成数据补全
;sz_rebuild_addr1=10.20.33.2
;sz_rebuild_port1=39128


[hqdf_rcgw]
rcgw_markets=sh,sz,shfe,czce,dce,ine,cffex  ;支持的市场类别。以逗号分隔，和下面市场key对应,目前支持shfe、czce、dce、ine、sh、sz、cffex
                                         ;shfe上期所, czce郑商所, dce大商所, ine上期能源，sh上交所，sz深交所，cffex中金所
timeout=30  							 ;超时时间30秒，用于冷备切换

[hqdf_rcgw_hot]
server_enable=1							 ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.168                ;接收网关HQReceiverGW IP
server_port=9004                         ;接收网关HQReceiverGW 端口

[hqdf_rcgw_cold]
server_enable=1							 ;地址开关控制配置。0-表示不生效，1-表示地址生效
server_addr=192.168.1.169                ;接收网关HQReceiverGW IP
server_port=9005                         ;接收网关HQReceiverGW 端口