username="nsq_sdk_u1"       #登陆用户名,如果有特殊字符#、;等，必须加双引号
password="nsq_sdk_p1"       #登陆密码,如果有特殊字符#、;等，必须加双引号
output_dest=0               #行情数据输出 0:屏幕 1:csv文件 2:屏幕和csv文件 默认0。32位demo程序仅支持输出到屏幕，该配置项不起作用
sh_codes=                   #订阅上海市场代码，sh_codes=为空表示订阅上海全市场代码；sh_codes=600570,000001 表示订阅2支代码
sz_codes=                   #订阅深圳市场代码，sz_codes=为空表示订阅深圳全市场代码；sz_codes=000001 表示订阅1支代码
shhkt_codes=                #订阅沪港股通代码，使用方法同上
szhkt_codes=                #订阅深港股通代码，使用方法同上
neeq_codes=                 #订阅股转市场代码，使用方法同上
bj_codes=                   #订阅北京市场代码，使用方法同上
shfe_codes=                 #订阅上期所市场代码，使用方法同上
ine_codes=                  #订阅上期能源市场代码，使用方法同上
cffex_codes=                #订阅中金所市场代码，使用方法同上
czce_codes=                 #订阅郑商所市场代码，使用方法同上
dce_codes=                  #订阅大商所市场代码，使用方法同上
ExchangeID=1                #逐笔重建请求参数，市场类型：1-上海，2-深圳
ChannelNo=2                 #逐笔重建请求参数，逐笔通道号
BeginSeqNo=1                #逐笔重建请求参数，请求逐笔起始序号,双闭区间[BeginSeqNo, EndSeqNo]
EndSeqNo=10                 #逐笔重建请求参数，请求逐笔结束序号