VER=1.0.0

EXE=fb_crr_hpc_on_future_theoretical_algorithm.so
EXE_D=fb_crr_hpc_on_future_theoretical_algorithm_d.so

DIR_LIST += ../../../fb_i_algorithm/include
DIR_LIST += ./src ../../common

include ../../../Makefile_so_tpl